---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

I chose to replicate the naive theories because of how it relates to my research interest in misinformation in how people develop their beliefs in ideas from social media such as the far right. This theory is based on the idea of what happens to theories when they are in conflict with previous notions of naive theories. I would like to know more about how people tend to keep their naive theories even after being proved wrong such as what factors affect this the most. I have found a lot of misinformation mostly from the internet and in person and as this study will be replicated as this I think it will be interesting as we will use crowdsource workers from the internet.

I would conduct the procedure by doing an experiment with stimuli presented to participants with MediaLab v1.21 software, which records the speed and accuracy of their judgments the same as the one before. I see myself doing this with common ideas proven wrong or ones that are more surprisingly similar to the one presented in the article. I would like to do this in order to get a better result but also making sure it doesn’t differ too much from the original. A hurdle may be because it's conducted online but I believe it will still yield a great result due to many naive theories nowadays coming from social media. I see this relating a lot more to how people compare naive theories to scientific ones when seeing them online says it's going to be conducted in that way. 


